name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Cython
        run: pip install Cython>=0.29.34

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pydoc-markdown

      - name: Create docs directory
        run: mkdir -p docs

      - name: Run static analysis with mypy
        run: |
          mypy --install-types --non-interactive .
          mypy --ignore-missing-imports .

      - name: Generate documentation with pydoc-markdown
        run: |
          pydoc-markdown pydoc.yml

      - name: Check generated documentation files
        run: |
          ls -la ./docs

      - name: Ensure docs directory is not empty
        run: |
          if [ ! "$(ls -A ./docs)" ]; then
            echo "Docs directory is empty, creating a placeholder file."
            touch ./docs/index.html
          fi

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          commit_message: "Auto-deploy documentation"
