name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Cython
        run: pip install Cython>=0.29.34

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pydoc-markdown

      - name: Create docs directory
        run: mkdir -p docs

      - name: Run static analysis with mypy
        run: |
          mypy --install-types --non-interactive .
          mypy --ignore-missing-imports .

      - name: Generate documentation with pydoc-markdown
        run: |
          pydoc-markdown pydoc.yml

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy existing files from gh-pages to pydoc directory
        run: |
          mkdir -p pydoc  # 创建 pydoc 文件夹
          cp -r gh-pages/* pydoc/ || true  # 将 gh-pages 分支中的所有文件复制到 pydoc 文件夹
          cp -r gh-pages/.* pydoc/ || true  # 确保隐藏文件也被复制

      - name: Clean gh-pages branch
        run: |
          cd gh-pages
          git rm -rf .  # 删除 gh-pages 分支中的所有文件
          cd ..

      - name: Force a change to ensure a commit
        run: |
          echo "Auto-deploy at $(date)" > pydoc/.autodeploy  # 创建一个临时文件以强制提交

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pydoc  # 指定 pydoc 文件夹作为发布目录
          commit_message: Auto-deploy documentation
          publish_branch: gh-pages
          allow_empty_commit: true  # 允许即使没有文件变化也提交
          keep_files: false  # 不保留 gh-pages 分支中的旧文件
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
