name: CI/CD Workflow

on:
  push:
    branches:
      - main  # 只在推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # 根据你的项目需求选择合适的 Python 版本

      - name: Clean build environment
        run: |
          pip install --upgrade pip setuptools wheel
          pip uninstall -y setuptools
          pip install --upgrade setuptools

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cython

      - name: Install PyYAML
        run: |
          pip install --only-binary :all: pyyaml==6.0

      - name: Install remaining dependencies
        run: |
          pip install -r requirements.txt  # 安装运行时依赖
          pip install mypy pydoc-markdown==4.0.0  # 安装开发工具依赖

      - name: Create docs directory
        run: mkdir -p docs  # 创建 docs 目录

      - name: Run static analysis with mypy
        run: |
          mypy --install-types --non-interactive .
          mypy --ignore-missing-imports .  # 检查项目根目录下的所有文件

      - name: Generate documentation with pydoc-markdown
        run: |
          pydoc-markdown --config-file pydoc.yml  # 确保有 pydoc.yml 配置文件

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # 指定文档生成的目录
          commit_message: "Auto-deploy documentation"
