name: CI/CD Workflow

on:
  push:
    branches:
      - main  # 只在推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Clean build environment
        run: |
          pip install --upgrade pip setuptools wheel
          pip cache purge  # 清理 pip 缓存

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cython3

      - name: Install PyYAML
        run: |
          pip install --only-binary :all: pyyaml==6.0.1

      - name: Install remaining dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy pydoc-markdown==4.0.0

      - name: Create docs directory
        run: mkdir -p docs

      - name: Run static analysis with mypy
        run: |
          mypy --install-types --non-interactive .
          mypy --ignore-missing-imports .

      - name: Generate documentation with pydoc-markdown
        run: |
          pydoc-markdown --config-file pydoc.yml

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: "Auto-deploy documentation"
